### PR TITLE
Optimize the algorithm to Radix Tree

### PR DESCRIPTION
**Pull request by Harry969**
I improved the insertion and search logic of the compressed prefix tree, simplified the node insertion process, merged redundant node splitting and prefix update operations, and thus improved the insertion efficiency. The algorithm for common prefix search was optimized, which reduced unnecessary string comparisons and improved performance. In terms of memory management, we improved the prefix storage method to avoid storing the complete prefix string in each node, thereby reducing memory usage. The overall performance of the tree was improved, especially the response speed and memory utilization in high concurrency and large-scale data processing, while ensuring the simplicity and maintainability of the code.

### CODE REVIEW

**Comment by Harry969** [comment]
This time I enhanced the intelligence and performance of the completion function. By introducing intelligent sorting, we ensure that words that fully match the prefix are displayed first, and shorter words and common words are given higher weights, thereby providing more accurate completion suggestions. I also implemented fuzzy matching and sorting by relevance to further improve the user experience. In addition, memory management was optimized, using slices to pre-allocate memory, and an efficient sorting algorithm was adopted to improve performance. The weight calculation of the completion results has also been improved, taking into account the prefix matching degree, word length and frequency of use, ensuring a more flexible and intelligent completion mechanism.

**Comment by Harry969** [comment]
The first optimization was to compress the tree algorithm by improving the insertion logic and implementing an efficient search mechanism❤️. The second optimization added the functions of intelligent sorting, fuzzy matching, and sorting by relevance.😼💕

**Comment by tongque0** [comment]
Dear contributor, your approach is very correct and effective. Thank you very much for your contribution. However, I wonder if you’ve noticed that the current prefix tree search only supports the first word, which is not user-friendly. I suggest splitting the input into words based on spaces, storing them in an array, and performing a prefix search on the last element of the array. This could be a good solution.

**Review by tongque0 — COMMENTED** [review]
Dear contributor, your approach is very correct and effective. Thank you very much for your contribution. However, I wonder if you’ve noticed that the current prefix tree search only supports the first word, which is not user-friendly. I suggest splitting the input into words based on spaces, storing them in an array, and performing a prefix search on the last element of the array. This could be a good solution.

**Comment by Harry969** [comment]
Okay, I'll improve it again.🫡💕

**Comment by tongque0** [comment]
yes，you are good。



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 5, 2024 19:37 PM
To: ***@***.***&gt;;
Cc: "JinTao ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [senorL/TransCLI] Optimize the algorithm to Radix Tree (PR #10)




 
Okay, I'll improve it again.🫡💕

**Pull request merged**
